### ISSUE TITLE
Allow adding a logo in the pattern-library header

### ISSUE THREAD

**Issue by gorkalaucirica** [LIN3S/PatternLibraryBuilder#15]
At configuration level we need an option to add company logo with ease.

Suggested configuration:

```yaml
lin3s_pattern_library_builder:
     theme:
          title: '@AppBundle/svg/logo.svg.twig'
          description: 'Design system'
          custom_styles: []
     templates_config_files_path: 'some-dir'
```

The goal is to make `theme.title` flexible to allow a simple string or a twig template that can render whatever the developer wants.

Maybe we can look for `@` to paint the twig template, otherwise paint the title as string
