### ISSUE TITLE
Custom status colors

### ISSUE THREAD

**Issue by gorkalaucirica** [LIN3S/PatternLibraryBuilder#47]
Allow adding via config a key value array defining colors for each status.

Example config:

```yml
lin3s_pattern_library_builder:
    theme:
         status:
             todo: '#f00'
             done: '#0f0'
             deprecated: '#000'
```
